name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        run: |
          # Add commands to copy files to your EC2 instance
          # Example: scp -r path/to/local/files/ ec2-user@your-ec2-ip:/path/on/ec2/
          # You might need to adjust this command based on your project structure

      - name: SSH into EC2 and restart server
        run: |
          # Add commands to SSH into your EC2 instance and restart the server
          # Example: ssh ec2-user@your-ec2-ip "sudo service apache2 restart"
          # You might need to adjust this command based on your web server